sudo: false

language: r

warnings_are_errors: false

os:
  - linux
  # - osx

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - export PATH=$(perl -e 'print join(":", grep { !m{/opt/python/} } split /:/, $ENV{PATH})')
  - source travis/install.sh

after_failure:
  - source travis/after_failure.sh

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages:
  - rstudio/reticulate
  - rstudio/tensorflow

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev

notifications:
  email:
    recipients:
      - terrytangyuan@gmail.com
    on_success: never
    on_failure: always