sudo: false

language: r

warnings_are_errors: false

os: linux

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - export PATH=$(perl -e 'print join(":", grep { !m{/opt/python/} } split /:/, $ENV{PATH})')
  - source travis_install.sh

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev

env:
  - TENSORFLOW_TEST_EXAMPLES="1"
    R_GCTORTURE="25"
