sudo: false

language: r

warnings_are_errors: false

env:
  global:
    - TENSORFLOW_TEST_EXAMPLES="1"

os:
  - linux
  # - osx

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R -e 'tensorflow::install_tensorflow(version = "1.3.0")'
  - mkdir inst/examples
  - cp -R vignettes/examples/* inst/examples

addons:
  apt:
    packages:
      - openmpi-bin
